import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headers from "@/comp/Headers";
import { Inter } from "next/font/google";

const inter=Inter({subsets:["latin"]});



export const metadata = {
  title: "Jio Cinema Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} antialiased`}
      >
        <Headers/>
        {children}
      </body>
    </html>
  );
}
